# For HTTPS
@HostAddress = https://localhost:7085

# For HTTP
# @HostAddress = http://localhost:5199

### Get metadata
GET {{HostAddress}}/odata/$metadata
Accept: application/json

###
GET {{HostAddress}}/odata/Customers
Accept: application/json

###
GET {{HostAddress}}/odata/Customers/GetCustomerByName(name='Customer1')
Accept: application/json

###
POST {{HostAddress}}/odata/Customers
Content-Type: application/json

{
   "id": 0,
   "name": "John Doe",
   "customerType": "regular, premium"
}

###
PATCH {{HostAddress}}/odata/Customers(2)
Content-Type: application/json

{
  "customerType": "regular, vip"
}